language: ruby
sudo: false
cache: bundler
bundler_args: ""
branches:
  only: master
rvm:
  - 2.1.5
  - 2.2.4
  - 2.3.1
  - 2.4.0
gemfile:
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
matrix:
  exclude:
    - rvm: 2.1.5
      gemfile: gemfiles/rails50.gemfile
