language: ruby
cache: bundler
before_install: gem install bundler
bundler_args: "" # make bumping versions not break all tests
branches:
  only: master
rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
gemfile:
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile
  - gemfiles/rails52.gemfile
